### ISSUE TITLE
[FEATURE] Create springboot/springbatch interface

### ISSUE THREAD

**Issue by Zabdel** [hubertqc/selinux_springbatch#12]
**Describe the bug**

Lors de l'exécution d'un batch spring batch via systemctl  ce dernier pop une erreur java :
java.net.ConnectException: Permission denied (connect failed) sur une un appel au registry kafka: https://{dnsING}:8443/

**To Reproduce**
Steps to reproduce the behavior.
Installer une application springboot sur le port 8443 
et installer un batch spring batch faisant une appel sur une remote url sur le port 8443 et au préable 
vérifier que les modules springbatch.te and springboot.te sont bien installé sur la machine

**Expected behavior**
allow java springbatch  to call a remote url with port 8443

**AVC denial messages**
type=AVC msg=audit(1720542610.990:784): avc:  denied  { name_connect } for  pid=2576 comm="java" dest=8443 scontext=system_u:system_r:springbatch_t:s0 tcontext=system_u:object_r:springboot_port_t:s0 tclass=tcp_socket permissive=0

**Platform (please complete the following information):**
 - Rhel 8 
 -Software stack [e.g. Java VM, Springboot framework, ...]

**Additional context**
allowed SE rule 
![image](https://github.com/user-attachments/assets/6836a0d4-f496-4cf1-bda4-8c5ff9a2a02c)

**Comment by hubertqc** [comment]
Regarding  AVC for `springbatch_t`:
> avc: denied { name_connect } for pid=2576 comm="java" dest=8443 scontext=system_u:system_r:springbatch_t:s0 tcontext=system_u:object_r:springboot_port_t:s0 tclass=tcp_socket permissive=0

The `springbatch_t` process is denied connection to the 8443/TCP port because the latter is labeled as `springboot_port_t`, probably because a Springboot application service is listening on port 8443/TCP on the very same host, but so far the SELinux policy does not allow such connection.

Solution is to create an additional rule to allow `springbatch_t` to connect to `springboot_port_t`.

**Comment by hubertqc** [comment]
@Zabdel: le problème de connexion du batch Spring à une appli Springboot en mode service sera résolu avec la release 0.9.0 à venir. Une fois le module SELinux mis à jour sur la machine, il faudra basculer le nouveau booléen `allow_springbatch_connectto_springboot` à `true`.

En revanche, il y a deux trois bricoles à explorer au regard des AVC qui apparaissent sur la copie d'écran que tu as postée:
- Une application Springboot (processus en `springboot_t`) essaie ou a essayé de se mettre en écoute sur un port TCP classé en `http_port_t`, il faut changer le type SELinux du port en question pour `springboot_port_t` (manuellement avec la commande  `semanage` ou avec une ressource Ansible de type `seport`) si ça n'a pas déjà été fait ;

- Une application Springboot (processus en `springboot_t`) essaie ou a essayé d'exécuter au moins un fichier classé en `springboot_var_t`, ce n'est pas normal et ça ne doit pas être autorisé en aucune façon. Il faut déterminer les caractéristiques du (ou des)  fichier(s) en question: emplacement(s), nom(s), contenu/but, créateur, ... du (ou des) fichier(s) pour savoir si la tentative d'exécution est légitime/licite et si oui alors comment reclasser (et éventuellement déplacer à un endroit plus logique) le (ou les) fichier(s) pour permettre l'exécution.

**Comment by Laurent-Gaillard** [comment]
Attention, dans la recette ansible il faut impérativement que springboot soit installé en premier avant le springbatch pour que cela soit effectif. Sinon il ne prendra pas en compte le paramètre optionnel.

**Comment by Laurent-Gaillard** [comment]
Pour activer la connexion de springbatch à springboot:

1. Installer le module springboot
2. Installer le module springbatch
3. Passer le booléen à true:
en ligne de commande:
     setsebool -P allow_springbatch_connectto_springboot true
ou
     semanage boolean -m --on allow_springbatch_connectto_springboot

avec ansible :
     - name: Set allow_springbatch_connectto_springboot boolean to allow spingbatch to connect to springboot and keep it persistent across reboots
       seboolean:
         name: allow_springbatch_connectto_springboot
         state: yes
         persistent: yes
